version: "3.8"

services:
  appointment:
    build:
      context: ./AppointmentService
    container_name: appointment_service
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - mongodb
    volumes:
      - ./AppointmentService:/app
    
  doctor:
    build:
      context: ./DoctorService
    container_name: doctor_service
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - mongodb
    volumes:
      - ./DoctorService:/app
  
  patient:
    build:
      context: ./PatientService
    container_name: patient_service
    ports:
      - "5002:5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - mongodb
    volumes:
      - ./PatientService:/app
  
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: